### ISSUE TITLE
KeyError: 'broadcast' when update to sdk robomaster-0.1.1.65

### ISSUE THREAD

**Issue by tianb03** [dji-sdk/RoboMaster-SDK#57]
I have updated to robomaster-0.1.1.65, in ubuntu 20.04 through 
`pip3 install --upgrade robomaster`

And also git pull the source code to test the examples.

Seems now I cannot execute all the scripts in multi_drone cos it will report 
`KeyError: 'broadcast'`
when retrieve the broadcast address from ipinfo. In tool.py line 106.

So I downgraded to robomaster-0.1.1.63.

**Comment by drezew** [comment]
In Ubuntu 21.10 and  robomaster-0.1.1.65 I also got the same error:

Traceback (most recent call last):
  File "/home/drezew/tmp/drones/main.py", line 86, in <module>
    multi_drone.initialize(robot_num=2)
  File "/home/drezew/.pyenv/versions/drones/lib/python3.8/site-packages/multi_robomaster/multi_robot.py", line 272, in initialize
    self._robot_host_list = self._client.scan_multi_robot(robot_num)
  File "/home/drezew/.pyenv/versions/drones/lib/python3.8/site-packages/multi_robomaster/tool.py", line 320, in scan_multi_robot
    return self._conn.scan_multi_robot(num)
  File "/home/drezew/.pyenv/versions/drones/lib/python3.8/site-packages/multi_robomaster/tool.py", line 266, in scan_multi_robot
    robot_host_list = self._scan_host(num)
  File "/home/drezew/.pyenv/versions/drones/lib/python3.8/site-packages/multi_robomaster/tool.py", line 232, in _scan_host
    subnets, address = get_subnets()
  File "/home/drezew/.pyenv/versions/drones/lib/python3.8/site-packages/multi_robomaster/tool.py", line 106, in get_subnets
    broadcast = ipinfo['broadcast']
KeyError: 'broadcast'

**Comment by 2197808908a** [comment]
> I have updated to robomaster-0.1.1.65, in ubuntu 20.04 through `pip3 install --upgrade robomaster`
> 
> And also git pull the source code to test the examples.
> 
> Seems now I cannot execute all the scripts in multi_drone cos it will report `KeyError: 'broadcast'` when retrieve the broadcast address from ipinfo. In tool.py line 106.
> 
> So I downgraded to robomaster-0.1.1.63.

@tianb03 So now,rmtt_ros can not use?

**Comment by tianb03** [comment]
> > I have updated to robomaster-0.1.1.65, in ubuntu 20.04 through `pip3 install --upgrade robomaster`
> > And also git pull the source code to test the examples.
> > Seems now I cannot execute all the scripts in multi_drone cos it will report `KeyError: 'broadcast'` when retrieve the broadcast address from ipinfo. In tool.py line 106.
> > So I downgraded to robomaster-0.1.1.63.
> 
> @tianb03 So now,rmtt_ros can not use?

Simply downgrade to 0.1.1.63 and everything will be fine for rmtt_ros
